cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
    path('', views.cart_detail, name="cart_detail"),
]

perfectcushion/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name="index"),
    path('category/', views.category, name="category"),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('product/<int:prod_id>/', views.product, name='productInfo'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name="ProdCatDetail"),
    path('myview/ss', views.myview, name="myview"),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="category", blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to="product", blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    popularity = models.IntegerField(default=0)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, help_text="eg. youremail@anymail.com")

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2')

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.utils.translation import gettext as _
from django.contrib.auth.models import Group, User
from .forms import SignUpForm

def index(request):
    template = loader.get_template('index.html')
    return HttpResponse(template.render({}, request))
    # return HttpResponse("this is index view")


def category(request):
    template = loader.get_template('shop/category.html')
    return HttpResponse(template.render({}, request))

# # Category view
# def allProdCat(request, c_slug=None):
#     c_page = None
#     products = None
#     if c_slug != None:
#         c_page = get_object_or_404(Category, slug=c_slug)
#         products = Product.objects.filter(category=c_page, available=True)
#     else:
#         products = Product.objects.all().filter(available=True)
#     return render(request, 'shop/category.html', {'category':c_page, 'products':products})

# Category view
def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', 1))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'shop/category.html', {'category':c_page, 'products':products})



# Product View

def product(request, prod_id):
    product_info = get_object_or_404(Product, id=prod_id)
    # return render(request, 'shop/product.html', {'product': product_info})
    return render(request, 'shop/product_new.html', {'product': product_info})

def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
        popular = Product.objects.all().order_by('popularity')[:5]
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product': product, 'popular': popular})

def signupview(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            signup_user= User.objects.get(username=username)
            customer_group = Group.objects.get(name='Customer')
            customer_group.user_set.add(signup_user)
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

def myview(request):
    output = _("Welcome to my site.")
    return HttpResponse(output)


"""
d = {"id": 100, "name": John}
d["name"]
d.get("name", "blah")

"""

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">copy: Perfect Cushion. All Rights Reserved</p>
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
    <center>
        <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="Perfect Cushion Store"></a>
    </center>
</header>

shop/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Welcome Home</title>

  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
</head>
<body>
  <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  </p>
  <img src="{% static 'ribbon-banner.jpg' %}" alt="My image">
</body>
</html>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:darkseagreen;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Shop
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
                    {% for cat in links %}
                    <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                    <i class="fas fa-shopping-cart"></i>({% if item_count > 0 %}{{item_count}}{% endif %})
                </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
</nav>


<!--<nav>-->
    <!--<ul>-->
        <!--<li><a href="{% url 'shop:allProdCat' %}">All Products</a></li>-->
        <!--{% for cat in links %}-->
        <!--<li><a href="{{ cat.get_url }}">{{ cat.name }}</a></li>-->
        <!--{% endfor %}-->
        <!--<li>Your Cart()</li>-->
    <!--</ul>-->
<!--</nav>-->